---
title: "STAT 441 Project"
author: "Matthew Fultz"
date: "20/01/2020"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# Load in training data and summarize it
dat.orig <- read.csv("train.csv")

# Convert satisfied to factor variable
dat <- dat.orig
i <- which(dat.orig$satisfied==0)
dat$satisfied[i] = "No"
dat$satisfied[-i] = "Yes"
dat$satisfied <- as.factor(dat$satisfied)
```


```{r}
# Load the plyr library
library(plyr)

# Read in training csv 1
dat <- read.csv("test.csv")

# Read in the file containing mappings for .a, .b, .c, etc.
dat.blanks <- read.csv("blanks.csv")

# Set column names to map from
f <- c("", ".a", ".b", ".c", ".d", "NA")

# Loop through and relevel columns to eliminate .a, .b, .c, etc.
dat.blanks <- sapply(dat.blanks, function(x){as.character(x)})
for (i in 1:270){
  t <- as.vector(dat.blanks[i, c(-1)])
  dat[, i+1] <- mapvalues(dat[, i+1], f, t)
}

# Create dat columns for number of no answers, refusals, and dont knows
dat.char <- sapply(dat, function(x){as.character(x)})

dat$NoAnswers <- 
  sapply(1:nrow(dat.char), function(x){table(dat.char[x, ])["No answer"]})
dat$NoAnswers <- replace(dat$NoAnswers, is.na(dat$NoAnswers), 0)

dat$Refusals <- 
  sapply(1:nrow(dat.char), function(x){table(dat.char[x, ])["Refusal"]})
dat$Refusals <- replace(dat$Refusals, is.na(dat$Refusals), 0)

dat$DontKnows <- 
  sapply(1:nrow(dat.char), function(x){table(dat.char[x, ])["Don't know"]})
dat$DontKnows <- replace(dat$DontKnows, is.na(dat$DontKnows), 0)

dat$TotNonAnswers <- dat$NoAnswers + dat$DontKnows + dat$Refusals

dat$InterviewDayOfWeek <- 
  as.factor(weekdays(as.Date(paste0(dat$v134, "-", dat$v129, "-", dat$v125))))

# Save the dataframe
dat.save <- dat

# Write to csv
write.csv(dat, "Test1.csv")

```


```{r}
dat <- dat.save
# Impute missing values
factorVars <- c("v17", "v20", "v25", "v70", "v71", "v72", "v73", "v78", 
                "v102", "v103", "v154", "v155", "v158", "v159", "v160", 
                "v161", "v163", "v164", "v190", "v191", "cntry")
for (i in 1:270){
  dat[, i+1] <- 
    mapvalues(dat[, i+1], 
              c("Not available", "Refusal", "Don't know", "No answer"),
              rep(NA, 4))
  if (!(paste0("v", i) %in% factorVars)) {
    dat[, i+1] <- as.numeric(dat[, i+1])
  }
}

dat$InterviewDayOfWeek <- 
  as.factor(weekdays(as.Date(paste0(dat$v134, "-", dat$v129, "-", dat$v125))))


```

